/* ==================================================================
 * EclipseFormat.java - 5/10/2026 4:12:38 pm
 *
 * Copyright 2026 SolarNetwork.net Dev Team
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
 * 02111-1307 USA
 * ==================================================================
 */

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Stream;
import javax.xml.parsers.DocumentBuilderFactory;
import org.eclipse.jdt.core.ToolFactory;
import org.eclipse.jdt.core.formatter.CodeFormatter;
import org.eclipse.jface.text.Document;
import org.eclipse.text.edits.TextEdit;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;

/**
 * Format Java source files with an Eclipse formatter profile, including
 * comments.
 *
 * <p>
 * The {@code eclipse-format.jar} command line tool formats code but not
 * comments, because it does not pass {@link CodeFormatter#F_INCLUDE_COMMENTS}
 * to the Eclipse formatter. This program uses the Eclipse formatter included
 * in that jar, with the same settings, and accepts the same
 * {@code --config=<file>}, {@code --recursive}, and {@code --verbose}
 * arguments. Run it as a single-file source program:
 * </p>
 *
 * <pre>
 * java -cp eclipse-format.jar EclipseFormat.java --config=profile.xml --recursive src
 * </pre>
 *
 * <p>
 * Files generated by JAXB, which start with a "This file was generated by"
 * comment, are formatted without their comments, because the formatter breaks
 * the schema fragments in their Javadoc.
 * </p>
 *
 * @author matt
 * @version 1.0
 */
public class EclipseFormat {

	private static final String GENERATED_MARKER = "This file was generated by";

	private static final String USAGE = "Usage: EclipseFormat --config=<file> [--recursive] [--verbose] <target>";

	/**
	 * Format Java source files.
	 *
	 * @param args
	 *        the arguments
	 * @throws Exception
	 *         if any error occurs
	 */
	public static void main(String[] args) throws Exception {
		Path config = null;
		Path target = null;
		boolean recursive = false;
		boolean verbose = false;
		for ( String arg : args ) {
			if ( arg.startsWith("--config=") ) {
				config = Path.of(arg.substring("--config=".length()));
			} else if ( arg.equals("-r") || arg.equals("--recursive") ) {
				recursive = true;
			} else if ( arg.equals("-v") || arg.equals("--verbose") ) {
				verbose = true;
			} else if ( !arg.startsWith("-") && target == null ) {
				target = Path.of(arg);
			} else {
				System.err.println(USAGE);
				System.exit(1);
			}
		}
		if ( config == null || target == null ) {
			System.err.println(USAGE);
			System.exit(1);
		}

		final CodeFormatter formatter = ToolFactory.createCodeFormatter(loadSettings(config),
				ToolFactory.M_FORMAT_EXISTING);
		final List<Path> files;
		try (Stream<Path> paths = Files.walk(target, recursive ? Integer.MAX_VALUE : 1)) {
			files = paths.filter(p -> p.toString().endsWith(".java") && Files.isRegularFile(p)).sorted()
					.toList();
		}
		for ( Path file : files ) {
			if ( format(formatter, file) && verbose ) {
				System.out.println("Formatted " + file);
			}
		}
	}

	/**
	 * Load the formatter settings from an Eclipse formatter profile.
	 *
	 * <p>
	 * The tabulation and indentation defaults match those of
	 * {@code eclipse-format.jar}.
	 * </p>
	 *
	 * @param config
	 *        the profile to load
	 * @return the settings
	 * @throws Exception
	 *         if the profile cannot be loaded
	 */
	private static Map<String, String> loadSettings(Path config) throws Exception {
		final Map<String, String> settings = new HashMap<>();
		final NodeList nodes = DocumentBuilderFactory.newInstance().newDocumentBuilder()
				.parse(config.toFile()).getElementsByTagName("setting");
		for ( int i = 0; i < nodes.getLength(); i++ ) {
			final Element setting = (Element) nodes.item(i);
			settings.put(setting.getAttribute("id"), setting.getAttribute("value"));
		}
		settings.putIfAbsent("org.eclipse.jdt.core.formatter.tabulation.char", "mixed");
		settings.putIfAbsent("org.eclipse.jdt.core.formatter.tabulation.size", "4");
		settings.putIfAbsent("org.eclipse.jdt.core.formatter.indentation.size", "4");
		return settings;
	}

	/**
	 * Format a Java source file.
	 *
	 * @param formatter
	 *        the formatter to use
	 * @param file
	 *        the file to format
	 * @return {@literal true} if the file was changed
	 * @throws IOException
	 *         if the file cannot be read or written
	 */
	private static boolean format(CodeFormatter formatter, Path file) throws IOException {
		final String source = Files.readString(file);
		final int kind = (isGenerated(source) ? CodeFormatter.K_COMPILATION_UNIT
				: CodeFormatter.K_COMPILATION_UNIT | CodeFormatter.F_INCLUDE_COMMENTS);
		final TextEdit edit = formatter.format(kind, source, 0, source.length(), 0,
				System.getProperty("line.separator", "\n"));
		if ( edit == null ) {
			System.err.println("Unable to format " + file + ", which may not be valid Java.");
			return false;
		}
		final Document doc = new Document(source);
		try {
			edit.apply(doc);
		} catch ( Exception e ) {
			System.err.println("Unable to format " + file + ": " + e.getMessage());
			return false;
		}
		final String result = doc.get();
		if ( result.equals(source) ) {
			return false;
		}
		Files.writeString(file, result);
		return true;
	}

	/**
	 * Test if a Java source starts with a generated file comment.
	 *
	 * @param source
	 *        the source to test
	 * @return {@literal true} if the comments before the package declaration
	 *         include the generated file marker
	 */
	private static boolean isGenerated(String source) {
		final int pkg = source.indexOf("package ");
		return source.substring(0, pkg < 0 ? source.length() : pkg).contains(GENERATED_MARKER);
	}

}
